name: Publish Docker


on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout rootfs
        uses: action/checkout@main
      - name: Publish to registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/PogunGun/NestJS
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "develop"
